services:
  planning:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./service_account.json:/app/service_account.json
    env_file:
      - .env

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${LOCAL_DB_PASSWORD}
      - MYSQL_DATABASE=${LOCAL_DB_NAME}
    volumes:
      - ./.docker/mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=${LOCAL_DB_USER}
      - PMA_PASSWORD=${LOCAL_DB_PASSWORD}
      - PMA_ARBITRARY=1

  consumer:
    env_file: ./.env
    image: python:3.9
    volumes:
      - ./consumer/consumer.py:/usr/local/bin/consumer.py
      - ./wait-for-rabbitmq.sh:/usr/local/bin/wait-for-rabbitmq.sh
    environment:
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
      - LOCAL_DB_NAME=${LOCAL_DB_NAME}
    depends_on:
      - db
    command:
      - "sh"
      - "-c"
      - "pip install pika && /usr/local/bin/wait-for-rabbitmq.sh && pip install mysql-connector-python && python3 /usr/local/bin/consumer.py"
