services:
  planning:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./service_account.json:/app/service_account.json
    env_file:
      - .env

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${LOCAL_DB_PASSWORD}
      - MYSQL_DATABASE=${LOCAL_DB_NAME}
    volumes:
      - ./.docker/mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=${LOCAL_DB_USER}
      - PMA_PASSWORD=${LOCAL_DB_PASSWORD}
      - PMA_ARBITRARY=1

  rabbitmq:
    image: rabbitmq:4-management
    container_name: planning-rabbit
    restart: always
    environment:
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_DEFAULT_USER=attendify
      - RABBITMQ_DEFAULT_VHOST=attendify
    ports:
      - "15672:15672" # RabbitMQ Management Plugin
      - "5672:5672" # AMQP
    volumes:
      - /home/frontend/volumes/rabbitmq/data:/var/lib/rabbitmq

  python:
    image: python:3.9
    container_name: configure-rabbitmq-planning
    volumes:
      - ./configure.py:/usr/local/bin/configure.py
      - ./wait-for-rabbitmq.sh:/usr/local/bin/wait-for-rabbitmq.sh
      - ../dbinit.py:/usr/local/bin/dbinit.py
    environment:
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    depends_on:
      - rabbitmq
    command:
      - "sh"
      - "-c"
      - "pip install pika && /usr/local/bin/wait-for-rabbitmq.sh && python3 /usr/local/bin/configure.py && pip install mysql-connector-python && python3 /usr/local/bin/dbinit.py"

  consumer:
    image: python:3.9
    volumes:
      - ./consumer/consumer.py:/usr/local/bin/consumer.py
      - ./wait-for-rabbitmq.sh:/usr/local/bin/wait-for-rabbitmq.sh
    environment:
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
      - LOCAL_DB_NAME=${LOCAL_DB_NAME}
    depends_on:
      - rabbitmq
      - db
    command:
      - "sh"
      - "-c"
      - "pip install pika && /usr/local/bin/wait-for-rabbitmq.sh && pip install mysql-connector-python && python3 /usr/local/bin/consumer.py"

  heartbeat:
    image: python:3.9
    volumes:
      - ./heartbeat/heartbeat.py:/usr/local/bin/heartbeat.py
      - ./wait-for-rabbitmq.sh:/usr/local/bin/wait-for-rabbitmq.sh
    environment:
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
      - LOCAL_DB_NAME=${LOCAL_DB_NAME}
    depends_on:
      - rabbitmq
      - db
    command:
      - "sh"
      - "-c"
      - "pip install pika && /usr/local/bin/wait-for-rabbitmq.sh && pip install mysql-connector-python && python3 /usr/local/bin/heartbeat.py"
