services:
  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile-tests
    volumes:
      - ./tests/integration:/tests
    depends_on:
      - webforms
      - db
      - rabbitmq
    networks:
      - planning_net
      - attendify_net
networks:
  attendify_net:
    internal: true
    name: attendify_net_testing

  planning_net:
    driver: bridge
