services:
  planning:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./service_account.json:/app/service_account.json
    env_file:
      - .env

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${LOCAL_DB_PASSWORD}
      - MYSQL_DATABASE=${LOCAL_DB_NAME}
    volumes:
      - ./.docker/mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=${LOCAL_DB_USER}
      - PMA_PASSWORD=${LOCAL_DB_PASSWORD}
      - PMA_ARBITRARY=1
    restart: always

  rabbitmq:
    image: rabbitmq:4-management
    container_name: planning-rabbit1
    environment:
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_DEFAULT_USER=attendify
      - RABBITMQ_DEFAULT_VHOST=attendify
    ports:
      - "15672:15672" # 15672:15672 RabbitMQ Management
      - "5672:5672" # "5672:5672" AMQP
    volumes:
      - /home/frontend/volumes/rabbitmq/data:/var/lib/rabbitmq
    restart: always

  python:
    image: python:3.9
    env_file: ./.env
    container_name: configure-rabbitmq-planning
    volumes:
      - ./configure.py:/usr/local/bin/configure.py
      - ../dbinit.py:/usr/local/bin/dbinit.py
    environment:
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    depends_on:
      - rabbitmq
    command:
      - "sh"
      - "-c"
      - "pip install pika && python3 /usr/local/bin/configure.py && pip install mysql-connector-python && python3 /usr/local/bin/dbinit.py"
    restart: on-failure

  consumer:
    env_file: ./.env
    image: python:3.9
    volumes:
      - ./consumer/consumer.py:/usr/local/bin/consumer.py
    environment:
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
      - LOCAL_DB_NAME=${LOCAL_DB_NAME}
    depends_on:
      - db
    command:
      - "sh"
      - "-c"
      - "pip install pika && pip install mysql-connector-python && python3 /usr/local/bin/consumer.py"
    restart: always

  heartbeat:
    env_file: ./.env
    image: python:3.9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./heartbeat/heartbeat.py:/usr/local/bin/heartbeat.py
    environment:
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
      - LOCAL_DB_NAME=${LOCAL_DB_NAME}
    depends_on:
      - rabbitmq
      - db
    command:
      - "sh"
      - "-c"
      - "pip install pika  && pip install mysql-connector-python && python3 /usr/local/bin/heartbeat.py"
    restart: always
