networks:
  attendify_net:
    driver: bridge
    name: attendify_net

  planning_net:
    driver: bridge

services:
  planning:
    build: .
    ports:
      - "30018:5000"
    volumes:
      - ./service_account.json:/app/service_account.json
    env_file:
      - .env

  webforms:
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile-webforms
    ports:
      - "30019:5000"
    volumes:
      - ./webforms:/usr/local/bin/webforms
    environment:
      - LOCAL_DB_HOST=db
      - LOCAL_DB_USER=root
      - LOCAL_DB_PASSWORD=root
      - LOCAL_DB_NAME=planning
    depends_on:
      - db
    networks:
      - planning_net

  db:
    image: mysql:8.0
    ports:
      - "30013:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${LOCAL_DB_PASSWORD}
      - MYSQL_DATABASE=${LOCAL_DB_NAME}
    volumes:
      - ./.docker/mysql-data:/var/lib/mysql
    networks:
      - planning_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "30012:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=${LOCAL_DB_USER}
      - PMA_PASSWORD=${LOCAL_DB_PASSWORD}
      - PMA_ARBITRARY=1
    restart: always
    networks:
      - planning_net

  rabbitmq:
    image: rabbitmq:4-management
    container_name: planning-rabbit1
    environment:
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_DEFAULT_USER=attendify
      - RABBITMQ_DEFAULT_VHOST=attendify
    ports:
      - "15672:15672" # 15672:15672 RabbitMQ Management
      - "5672:5672" # "5672:5672" AMQP
    volumes:
      - /home/frontend/volumes/rabbitmq/data:/var/lib/rabbitmq
    restart: always
    profiles:
      - dev
    networks:
      - planning_net

  python:
    image: python:3.9
    env_file: ./.env
    container_name: configure-rabbitmq-planning
    volumes:
      - ./configure.py:/usr/local/bin/configure.py
    environment:
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    command:
      - "sh"
      - "-c"
      - "pip install pika && python3 /usr/local/bin/configure.py "
    restart: on-failure
    profiles:
      - dev
    networks:
      - planning_net

  python2:
    image: python:3.9
    env_file: ./.env
    container_name: configure-database-planning
    volumes:
      - ./dbinit:/usr/local/bin/dbinit
    environment:
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    command:
      - "sh"
      - "-c"
      - "pip install pika &&  pip install mysql-connector-python && python3 /usr/local/bin/dbinit/usertable.py && python3 /usr/local/bin/dbinit/user_event_table.py && python3 /usr/local/bin/dbinit/event_session.py"
    profiles:
      - dbinit
      - dev
    networks:
      - planning_net

  consumer:
    env_file: ./.env
    image: python:3.9
    volumes:
      - ./consumer/consumer.py:/usr/local/bin/consumer.py
    environment:
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
      - LOCAL_DB_NAME=${LOCAL_DB_NAME}
    depends_on:
      - db
    command:
      - "sh"
      - "-c"
      - "pip install pika && pip install mysql-connector-python && python3 /usr/local/bin/consumer.py"
    restart: always
    networks:
      - planning_net
      - attendify_net

  heartbeat:
    env_file: ./.env
    image: python:3.9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./heartbeat/heartbeat.py:/usr/local/bin/heartbeat.py
    environment:
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
      - LOCAL_DB_NAME=${LOCAL_DB_NAME}
    depends_on:
      - db
    command:
      - "sh"
      - "-c"
      - "pip install pika  && pip install mysql-connector-python && python3 /usr/local/bin/heartbeat.py"
    restart: always
    networks:
      - planning_net
      - attendify_net

  consumer-user-link:
    env_file: ./.env
    image: python:3.9
    volumes:
      - ./consumer/consumer_user_link_eventsession.py:/usr/local/bin/consumer_user_link_eventsession.py
    environment:
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
      - LOCAL_DB_NAME=${LOCAL_DB_NAME}
    depends_on:
      - db
    command:
      - "sh"
      - "-c"
      - "pip install pika && pip install mysql-connector-python && python3 /usr/local/bin/consumer_user_link_eventsession.py"
    restart: always
    networks:
      - planning_net
      - attendify_net

  synchronizer-db:
    image: python:3.9
    env_file: .env
    volumes:
      - ./synchronizer:/usr/local/bin/synchronizer
      - ./service_account.json:/app/service_account.json
      - ./producer:/usr/local/bin/producer

    command:
      - "sh"
      - "-c"
      - "pip install pika && pip install mysql-connector-python google-api-python-client google-auth-httplib2 google-auth-oauthlib && python3 -u /usr/local/bin/synchronizer/sync.py"
    restart: always
    depends_on:
      - db
    networks:
      - planning_net
      - attendify_net
