name: Attendify Planning CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - test
      - main
  pull_request:
    branches:
      - test
      - main

jobs:
  docker-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create service account JSON
        run: |
          mkdir -p planning
          echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" > planning/service_account.json

      - name: Build Docker image
        run: |
          docker build -t attendify-planning planning/

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Install test dependencies & run unit tests
        run: |
          pip install -r planning/tests/unit/requirements.txt
          pytest planning/tests/unit

  # Deploy to test only on the test branch
  deploy-test:
    name: Deploy to Test Server
    runs-on: ubuntu-latest
    needs: docker-ci
    if: github.ref == 'refs/heads/test'
    steps:
      - name: Deploy to test via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 60022
          script: |
            cd ~/attendify/test-environment/testing-Planning/attendify-planning
            git pull origin test
            cd ~/attendify/test-environment/testing-Planning/attendify-planning/planning
            docker compose down
            docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d --build

    # Deploy to production only on the main branch
  deploy-prod:
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    needs: docker-ci
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to production via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 60022
          script: |
            cd ~/attendify/attendify-planning
            git pull origin main
            cd ~/attendify/attendify-planning/planning
            docker compose down
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build
